import { useParams } from "react-router-dom";
import { Button, Card, PageHeader, TextLink } from "../components/ui";
import { formatDate } from "../lib/format";
import { useStore } from "../mock/store";

export function ReportPage() {
  const { id } = useParams();
  const { reports, getCase, getClient } = useStore();
  const report = reports.find((r) => r.id === id);
  const c = report ? getCase(report.caseId) : undefined;
  const client = c ? getClient(c.clientId) : undefined;

  if (!report || !c || !client) {
    return (
      <Card>
        <p>Report not found.</p>
        <TextLink to="/history">History</TextLink>
      </Card>
    );
  }

  return (
    <>
      <PageHeader
        title={report.title}
        subtitle={`${client.name} · ${report.productCode} · ${formatDate(report.generatedAt)}`}
        actions={
          <Button className="no-print" variant="secondary" onClick={() => window.print()}>
            Print / PDF
          </Button>
        }
      />
      <Card>
        <p>
          <strong>Type:</strong> {report.type.replace("_", " ")}
        </p>
        <p>{report.summary}</p>
        <h2 style={{ fontSize: "1.1rem", marginTop: 20 }}>Domain scores</h2>
        {report.domains.map((d) => (
          <div className="report-domain" key={d.name}>
            <span>{d.name}</span>
            <span>
              <strong>{d.score}</strong>
              <span className="faint"> · {d.range}</span>
            </span>
          </div>
        ))}
        <h2 style={{ fontSize: "1.1rem", marginTop: 24 }}>Narrative</h2>
        <p>{report.narrative}</p>
        <p className="faint" style={{ marginTop: 24 }}>
          Demo report only. Not generated by WPS scoring software and not for
          clinical decision-making.
        </p>
        <div className="row-actions no-print" style={{ marginTop: 16 }}>
          <TextLink to={`/cases/${c.id}`}>Back to case</TextLink>
          <TextLink to={`/clients/${client.id}`}>Client home</TextLink>
        </div>
      </Card>
    </>
  );
}
